Create routes
tanselbay1/pokedex_frontend pull request #2
Opened 2023-07-26 10:55 UTC by tanselbay1

### With this Pr
- Routes(root, pokemon-list) initialized
- Navbar menu added
- Footer added
- As a dummy, pokedex image added.

2023-07-26 18:01 UTC, kapaha requested changes
We should replace all anchor tags that link to internal pages with React router Link / NavLink components instead, so that the page loads on the client instead of server

2023-07-28 15:05 UTC, tanselbay1 commented
Change requests completed

2023-07-31 12:19 UTC, kapaha commented
LGTM 👍🏻

2023-07-31 12:19 UTC, kapaha approved these changes

2023-07-31 12:19 UTC, merged